# Generated by Django 2.1.7 on 2020-05-09 05:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyTable',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=500)),
                ('symbol', models.CharField(db_column='symbol', max_length=20)),
                ('iso', models.CharField(db_column='iso', max_length=100)),
                ('date_create', models.DateTimeField(db_column='date_create', default=django.utils.timezone.now)),
                ('date_update', models.DateTimeField(db_column='date_update', default=django.utils.timezone.now)),
                ('date_delete', models.DateTimeField(db_column='date_delete', default=None, null=True)),
            ],
            options={
                'db_table': 'currency',
                'ordering': ('date_create',),
            },
        ),
        migrations.CreateModel(
            name='DomainTable',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=1000)),
                ('offer_description_max_length', models.IntegerField(db_column='offer_description_max_length', help_text='Define the max length of offer’s description allowed by the marketplace.')),
                ('date_create', models.DateTimeField(db_column='date_create', default=django.utils.timezone.now)),
                ('date_update', models.DateTimeField(db_column='date_update', default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'domain',
                'ordering': ('date_create',),
            },
        ),
        migrations.CreateModel(
            name='PersonTable',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=500)),
                ('country', models.CharField(db_column='country', max_length=200)),
                ('time_zone', models.CharField(db_column='time_zone', max_length=100)),
                ('date_create', models.DateTimeField(db_column='date_create', default=django.utils.timezone.now)),
                ('date_update', models.DateTimeField(db_column='date_update', default=django.utils.timezone.now)),
                ('date_delete', models.DateTimeField(db_column='date_delete', default=None, null=True)),
                ('_raw', models.TextField(blank=True, db_column='_raw', null=True)),
                ('currency', models.ForeignKey(help_text='FK on Currency (if the Person default Currency is specified)', on_delete=django.db.models.deletion.CASCADE, related_name='cur_currency', to='rest_api.CurrencyTable')),
                ('domain', models.ForeignKey(help_text='FK on Domain', on_delete=django.db.models.deletion.CASCADE, related_name='dom_domain', to='rest_api.DomainTable')),
            ],
            options={
                'db_table': 'person',
                'ordering': ('date_create',),
            },
        ),
        migrations.CreateModel(
            name='TagTable',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=500)),
                ('date_create', models.DateTimeField(db_column='date_create', default=django.utils.timezone.now)),
                ('date_update', models.DateTimeField(db_column='date_update', default=django.utils.timezone.now)),
                ('date_delete', models.DateTimeField(db_column='date_delete', default=None, null=True)),
            ],
            options={
                'db_table': 'tag',
                'ordering': ('date_create',),
            },
        ),
    ]
